  # - "image-pull-secret"

windowsMonitoring:
  ## Deploys the windows-exporter and Windows-specific dashboards and rules (job name must be 'windows-exporter')
  enabled: false

## Configuration for prometheus-windows-exporter
## ref: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-windows-exporter
##
prometheus-windows-exporter:
  ## Enable ServiceMonitor and set Kubernetes label to use as a job label
  ##
  prometheus:
    monitor:
      enabled: true
      jobLabel: jobLabel

  releaseLabel: true

  ## Set job label to 'windows-exporter' as required by the default Prometheus rules and Grafana dashboards
  ##
  podLabels:
    jobLabel: windows-exporter

  ## Enable memory and container metrics as required by the default Prometheus rules and Grafana dashboards
  ##
  config: |-
    collectors:
      enabled: '[defaults],memory,container'

## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:

  ## Deploy alertmanager
  ##
  enabled: true

  # Optional: Override the namespace where Alertmanager will be deployed.
  namespaceOverride: ""

  ## Annotations for Alertmanager
  ##
  annotations: {}

  ## Additional labels for Alertmanager
  ##
  additionalLabels: {}

  ## API that Prometheus will use to communicate with alertmanager. Possible values are v1, v2
  ##
  apiVersion: v2

  ## @param alertmanager.enableFeatures Enable access to Alertmanager disabled features.
  ##
  enableFeatures: []

  ## Create dashboard configmap even if alertmanager deployment has been disabled
  ##
  forceDeployDashboards: false

  ## Network Policy configuration
  ##
  networkPolicy:
    # -- Enable network policy for Alertmanager
    enabled: false

    # -- Define policy types. If egress is enabled, both Ingress and Egress will be used
    # Valid values are ["Ingress"] or ["Ingress", "Egress"]
    ##
    policyTypes:
      - Ingress

    # -- Gateway (formerly ingress controller) configuration
    ##
    gateway:
      # -- Gateway namespace
      ##
      namespace: ""
      # -- Gateway pod labels
      ##
      podLabels: {}
      # app.kubernetes.io/name: ingress-nginx

    # -- Additional custom ingress rules
    ##
    additionalIngress: []
    # - from:
    #   - namespaceSelector:
    #       matchLabels:
    #         name: another-namespace
    #     podSelector:
    #       matchLabels:
    #         app: another-app
    # - from:
    #     - podSelector:
    #         matchLabels:
    #           app.kubernetes.io/name: loki
    #   ports:
    #     - port: 9093
    #       protocol: TCP

    # -- Configure egress rules
    ##
    egress:
      # -- Enable egress rules. When enabled, policyTypes will include Egress
      ##
      enabled: false
      # -- Custom egress rules
      ##
      rules: []
      # - to:
      #   - namespaceSelector: {}
      #     podSelector:
      #       matchLabels:
      #         name: smtp-relay
      #   ports:
      #   - port: 25
      #     protocol: TCP

    # -- Enable rules for alertmanager cluster traffic
    ##
    enableClusterRules: true

    # -- Configure monitoring component rules
    ##
    monitoringRules:
      # -- Enable ingress from Prometheus
      ##
      prometheus: true
      # -- Enable ingress for config reloader metrics
      ##
      configReloader: true

